// Product Data - Replace with your actual affiliate links
// All products with category and price information
const allProductsData = [
    {
        "id": 7001,
        "title": " DASH Mini Waffle Maker Machine for Individuals, Paninis, Hash Browns, &amp; Other On the Go Breakfast, Lunch, or Snacks, with Easy to Clean, Non-Stick Sides, Red Heart 4 Inch Click to see full view       7 VIDEOS  Ask Rufus  Can it make pancakes?   Does it have temperature control?   Is it easy to store?   Ask something else DASH Mini Waffle Maker Machine for Individuals, Paninis, Hash Browns, & Other On the Go Breakfast, Lunch, or Snacks, with Easy to Clean, Non-Stick Sides, Red Heart 4 Inch",
        "price": "9.99",
        "priceValue": 9.99,
        "category": "appliances",
        "image": "https://m.media-amazon.com/images/I/81eA9ukyqDL._AC_SL1500_.jpg",
        "rating": 4.6,
        "affiliateLink": "https://amzn.to/4n6Tx4x",
        "featured": false
    },
    {
        "id": 7002,
        "title": "Uncrustable Sandwich Maker, Sandwich Pocket Circle Shape Cutter & Sealer for Kids Breakfast and Lunchboxes, Light Blue, 3.7Inch",
        "price": "7.98",
        "priceValue": 7.98,
        "category": "appliances",
        "image": "https://m.media-amazon.com/images/I/71307GHCqyL._AC_SL1080_.jpg",
        "rating": 4.6,
        "affiliateLink": "https://amzn.to/3VpZe1v",
        "featured": false
    },
    {
        "id": 7003,
        "title": "KitchenAid All Purpose Kitchen Shears with Protective Sheath Durable Stainless Steel Scissors, Dishwasher Safe, Soft Grip Comfort Handle, 8.72 Inch, Black Visit the KitchenAid Store",
        "price": "9.99",
        "priceValue": 9.99,
        "category": "appliances",
        "image": "https://m.media-amazon.com/images/I/615Rolz2qVL._AC_SL1500_.jpg",
        "rating": 4.8,
        "affiliateLink": "https://amzn.to/46A1okq",
        "featured": false
    },
    {
        "id": 7004,
        "title": "Oil Sprayer for Cooking,100ml Olive Oil Spritzer,Oil Sprayer for Air Fryer, Salad,BBQ,Roasting",
        "price": "9.98",
        "priceValue": 9.98,
        "category": "appliances",
        "image": "https://m.media-amazon.com/images/I/61MxYsQLWIL._AC_SL1500_.jpg",
        "rating": 4.3,
        "affiliateLink": "https://amzn.to/4nGqdSD",
        "featured": false
    },
    {
        "id": 7005,
        "title": "Ultrean Food Scale, Digital Kitchen Scale Weight Grams and Ounces for Baking Cooking and Meal Prep, 6 Units with Tare Function, 11lb (Batteries Included)",
        "price": "9.99",
        "priceValue": 9.99,
        "category": "appliances",
        "image": "https://m.media-amazon.com/images/I/71TV+iWbGlL._SL1500_.jpg",
        "rating": 4.6,
        "affiliateLink": "https://amzn.to/4mnnrjZ",
        "featured": false
    },
    {
        "id": 7006,
        "title": "KongNai Kitchen Funnel Set 4 Pack, Small and Large, Kitchen Gadgets Accessories Foldable Silicone Collapsible Funnels for Filling Water Bottle Liquid Transfer Food Grade",
        "price": "5.99",
        "priceValue": 5.99,
        "category": "appliances",
        "image": "https://m.media-amazon.com/images/I/51DIEigRxcL._SL1000_.jpg",
        "rating": 4.6,
        "affiliateLink": "https://amzn.to/4pveMPi",
        "featured": false
    },
    {
        "id": 7007,
        "title": "L LOHAS LED Night Lights 0.3W 3000K Soft White 2-Pack",
        "price": "9.99",
        "priceValue": 9.99,
        "category": "appliances",
        "image": "https://m.media-amazon.com/images/I/91QXIWulzlL._AC_SL1500_.jpg",
        "rating": 4.6,
        "affiliateLink": "https://amzn.to/46pJOzb",
        "featured": false
    },
    {
        "id": 7008,
        "title": "Meat Chopper, 5 Curve Blades Ground Beef Masher, Heat Resistant Meat Masher Tool for Hamburger Meat, Ground Beef, Turkey and More, Nylon Hamburger Chopper Utensil Non-scratch Utensils",
        "price": "8.99",
        "priceValue": 8.99,
        "category": "appliances",
        "image": "https://m.media-amazon.com/images/I/51VPAZzOGlL._AC_.jpg",
        "rating": 4.7,
        "affiliateLink": "https://amzn.to/3Ieo9SJ",
        "featured": false
    },
    {
        "id": 7009,
        "title": "Spring Chef Stainless Steel Magnetic Measuring Spoons Set with Strong N45 Magnets, Heavy Duty Metal Kitchen Gadgets for Baking & Cooking, Fits in Most Kitchen Spice Jars, Set of 8 with Leveler, Black",
        "price": "9.99",
        "priceValue": 9.99,
        "category": "appliances",
        "image": "https://m.media-amazon.com/images/I/91hoojVnCKL._AC_SL1500_.jpg",
        "rating": 4.9,
        "affiliateLink": "https://amzn.to/4grbd8A",
        "featured": false
    },
    {
        "id": 7010,
        "title": "Elite Gourmet ETS623 BPA-Free Electric Citrus Juicer, Compact, Large Volume, Pulp Control, Oranges, Lemons, Limes, Grapefruits with Easy Pour Spout, 24oz, Black/Stainless Steel",
        "price": "13.99",
        "priceValue": 13.99,
        "category": "appliances",
        "image": "https://m.media-amazon.com/images/I/617Xb57Wd+L._AC_SL1500_.jpg",
        "rating": 4.5,
        "affiliateLink": "https://amzn.to/4mnq8SD",
        "featured": false
    },
    {
        "id": 7011,
        "title": "Elite Gourmet ESB100B Countertop Single Coiled Burner Electric Hot Plate, Temperature Control, Indicator Light, Easy to Clean, Black",
        "price": "11.99",
        "priceValue": 11.99,
        "category": "appliances",
        "image": "https://m.media-amazon.com/images/I/71Zj1Sr1KvL._AC_SL1500_.jpg",
        "rating": 4.4,
        "affiliateLink": "https://amzn.to/3Vo1shW",
        "featured": false
    },
    {
        "id": 7012,
        "title": "Electric Wine Opener Set - Automatic Electronic Bottle Openers with Greeting Card, Vacuum Stoppers, Wine Aerator, and Foil Cutter, Ideal Present for Wine Lovers, Party, and Home Entertaining",
        "price": "12.66",
        "priceValue": 12.66,
        "category": "appliances",
        "image": "https://m.media-amazon.com/images/I/61NOp5xMgeL._AC_SL1500_.jpg",
        "rating": 4.5,
        "affiliateLink": "https://amzn.to/4gqRMwy",
        "featured": false
    },
    {
        "id": 7013,
        "title": "bella 2 Slice Slim Toaster, Fits-anywhere™ Kitchenware, 6 Setting Shade Control with Reheat & Cancel Buttons, Fits sourdough, 10” Long Slot, Anti Jam & Auto Shutoff, 900 Watt, Oatmilk",
        "price": "24.99",
        "priceValue": 24.99,
        "category": "appliances",
        "image": "https://m.media-amazon.com/images/I/71zZ0tSkfHL._AC_SL1500_.jpg",
        "rating": 4.3,
        "affiliateLink": "https://amzn.to/4gpZDdO",
        "featured": false
    },
    {
        "id": 7014,
        "title": "Electric Salt and Pepper Grinder Set Automatic Battery Pepper Mill Shakers Adjustable Coarseness Upgraded Larger Capacity with Led Home and Kitchen Appliances for New House Warming Gifts",
        "price": "21.99",
        "priceValue": 21.99,
        "category": "appliances",
        "image": "https://m.media-amazon.com/images/I/710-4T+ExCL._AC_SL1500_.jpg",
        "rating": 4.4,
        "affiliateLink": "https://amzn.to/4poJJVb",
        "featured": false
    },
    {
        "id": 7015,
        "title": "Chefman Electric Kettle, 1.8L 1500W, Hot Water Boiler, Removable Lid for Easy Cleaning, Auto Shut Off, Boil-Dry Protection, Stainless Steel Filter, BPA Free, Borosilicate Glass Electric Tea Kettle",
        "price": "23.69",
        "priceValue": 23.69,
        "category": "appliances",
        "image": "https://m.media-amazon.com/images/I/81Igmra8QXL._AC_SL1500_.jpg",
        "rating": 4.5,
        "affiliateLink": "https://amzn.to/4gs2iUl",
        "featured": false
    },
    {
        "id": 7016,
        "title": "DASH Hot Air Popcorn Popper Maker with Measuring Cup to Portion Popping Corn Kernels + Melt Butter, 16 Cups - Aqua",
        "price": "19.49",
        "priceValue": 19.49,
        "category": "appliances",
        "image": "https://m.media-amazon.com/images/I/71ijvvCQU7L._AC_SL1500_.jpg",
        "rating": 4.2,
        "affiliateLink": "https://amzn.to/4gwNgN9",
        "featured": false
    },
    {
        "id": 7017,
        "title": "Hamilton Beach Electric Vegetable Chopper & Mini Food Processor, 3-Cup, 350 Watts, for Dicing, Mincing, and Puree, Black (72850)",
        "price": "19.99",
        "priceValue": 19.99,
        "category": "appliances",
        "image": "https://m.media-amazon.com/images/I/61BtxhTS8ZL._AC_SL1500_.jpg",
        "rating": 4.6,
        "affiliateLink": "https://amzn.to/4nv9mSC",
        "featured": false
    },
    {
        "id": 7018,
        "title": "OXO Good Grips Salad Spinner | Lettuce Spinner | Fruit Washer | Fruit Washing Bowl with Strainer | Vegetable Cleaner | Salad Cleaner | Lettuce Washer | 6.22 Quart Capacity",
        "price": "31.96",
        "priceValue": 31.96,
        "category": "appliances",
        "image": "https://m.media-amazon.com/images/I/81ZPSZ+A5rL._AC_SL1500_.jpg",
        "rating": 4.7,
        "affiliateLink": "https://amzn.to/4graUuu",
        "featured": false
    },
    {
        "id": 7019,
        "title": "OVENTE Electric Sandwich Maker with Non-Stick Plates, Indicator Lights, Cool Touch Handle, Easy to Clean and Store, Perfect for Cooking Breakfast, Grilled Cheese, Tuna Melts and Snacks, Black GPS401B",
        "price": "19.99",
        "priceValue": 19.99,
        "category": "appliances",
        "image": "https://m.media-amazon.com/images/I/71kgJsC53YL._AC_SL1500_.jpg",
        "rating": 4.3,
        "affiliateLink": "https://amzn.to/46dx004",
        "featured": false
    },
    {
        "id": 7020,
        "title": "Kusini Electric Fondue Pot Set - Chocolate Fondue Kit - Temperature Control, Detachable Serving Trays, & 4 Roasting Forks - Gift Set & Date Night Idea. Serve at Movie Night or Game Night.",
        "price": "15.99",
        "priceValue": 15.99,
        "category": "appliances",
        "image": "https://m.media-amazon.com/images/I/81eZyfg7N6L._AC_SL1500_.jpg",
        "rating": 4.4,
        "affiliateLink": "https://amzn.to/4prPp0I",
        "featured": false
    },
    {
        "id": 7021,
        "title": "Amazon Basics 2 Slice Toaster, With 6 Browning Settings, Extra Wide Slots For Bagels and Special Breads, Removable Easy-to-Clean Crumb Tray, Cancel/Defrost/Bagel Buttons, 900W, Black & Silver",
        "price": "23.74",
        "priceValue": 23.74,
        "category": "appliances",
        "image": "https://m.media-amazon.com/images/I/71cmt6zgFHL._AC_SL1500_.jpg",
        "rating": 4.3,
        "affiliateLink": "https://amzn.to/3IsZ8Df",
        "featured": false
    },
    {
        "id": 7022,
        "title": "50 Pack (100-Piece) 24 oz Meal Prep Containers Reusable with Lids, Sturdy Leakproof & Food Safe, Microwave, Freezer, Dishwasher Safe Prep Containers, To Go Take Out Plastic Food Storage",
        "price": "23.99",
        "priceValue": 23.99,
        "category": "appliances",
        "image": "https://m.media-amazon.com/images/I/71oB3+94jBL._AC_SL1500_.jpg",
        "rating": 4.4,
        "affiliateLink": "https://amzn.to/48mOZCE",
        "featured": false
    },
    {
        "id": 7023,
        "title": "Metal 4 Pack Magnetic Spice Storage Rack Organizer for Refrigerator and Oven, Black Fridge Organizers and Storage",
        "price": "19.99",
        "priceValue": 19.99,
        "category": "appliances",
        "image": "https://m.media-amazon.com/images/I/51imrSup74L._AC_.jpg",
        "rating": 4.8,
        "affiliateLink": "https://amzn.to/4nvOGd4",
        "featured": false
    },
    {
        "id": 7024,
        "title": "Zulay Kitchen Powerful Milk Frother Wand With 2 Duracell Batteries - Ultra Fast Handheld Drink Mixer - Electric Whisk Foam Maker for Coffee, Lattes, Cappuccino, Matcha, Hot Chocolate & Creamer - Black",
        "price": "14.99",
        "priceValue": 14.99,
        "category": "appliances",
        "image": "https://m.media-amazon.com/images/I/811-tPSBMML._AC_SL1500_.jpg",
        "rating": 4.5,
        "affiliateLink": "https://amzn.to/3VTW0Dt",
        "featured": false
    },
    {
        "id": 7025,
        "title": "Bluetooth Speaker with HD Sound, Portable Wireless, IPX5 Waterproof, Up to 20H Playtime, TWS Pairing, BT5.3, for Home/Party/Outdoor/Beach, Stocking Stuffers, White Elephant Gifts for Adults (Black)",
        "price": "19.98",
        "priceValue": 19.98,
        "category": "appliances",
        "image": "https://m.media-amazon.com/images/I/81l7mB5LhsL._AC_SL1500_.jpg",
        "rating": 4.4,
        "affiliateLink": "https://amzn.to/4ptWRsf",
        "featured": false
    },
    {
        "id": 7026,
        "title": "BLACK+DECKER 1.5-Cup Electric Food Chopper, One Touch Pulse, 150W Motor, Stay-Sharp Blade, Dishwasher Safe",
        "price": "18.37",
        "priceValue": 18.37,
        "category": "appliances",
        "image": "https://m.media-amazon.com/images/I/815Gfj8hrhL._AC_SL1500_.jpg",
        "rating": 4.5,
        "affiliateLink": "https://amzn.to/4pl12GG",
        "featured": false
    },
    {
        "id": 7027,
        "title": "Victoria 8 Inches Cast Iron Tortilla Press, Roti Maker and Tortilladora, Pataconera Seasoned with Flaxseed Oil, Made in Colombia",
        "price": "21.62",
        "priceValue": 21.62,
        "category": "appliances",
        "image": "https://m.media-amazon.com/images/I/71ywI7XyJ-L._AC_SL1500_.jpg",
        "rating": 4.5,
        "affiliateLink": "https://amzn.to/3VTY1Q2",
        "featured": false
    },
    {
        "id": 7028,
        "title": "Geedel Rotary Cheese Grater, Kitchen Mandoline Vegetable Slicer with 3 Interchangeable Blades, Easy to Clean Grater for Fruit, Vegetables, Nuts",
        "price": "19.98",
        "priceValue": 19.98,
        "category": "appliances",
        "image": "https://m.media-amazon.com/images/I/71bxAXFOvrL._AC_SL1500_.jpg",
        "rating": 4.6,
        "affiliateLink": "https://amzn.to/4mtrFGR",
        "featured": false
    },
    {
        "id": 7029,
        "title": "DASH Mini Donut Maker Machine for Kid-Friendly Breakfast, Snacks, Desserts & More with Non-stick Surface, Makes 7 Doughnuts - Aqua",
        "price": "21.99",
        "priceValue": 21.99,
        "category": "appliances",
        "image": "https://m.media-amazon.com/images/I/81iUh5dKM3L._AC_SL1500_.jpg",
        "rating": 4.6,
        "affiliateLink": "https://amzn.to/46HOVMu",
        "featured": false
    },
    {
        "id": 7030,
        "title": "Brita Water Filter Pitcher for Tap and Drinking Water with 1 Standard Filter, Lasts 2 Months, 6-Cup Capacity, BPA Free, White",
        "price": "24.75",
        "priceValue": 24.75,
        "category": "appliances",
        "image": "https://m.media-amazon.com/images/I/71s7yQg7tjL._SL1500_.jpg",
        "rating": 4.5,
        "affiliateLink": "https://amzn.to/3Kbbvo4",
        "featured": false
    },
    {
        "id": 7031,
        "title": "DASH Rapid Egg Cooker: 6 Egg Capacity Electric Egg Cooker for Hard Boiled Eggs, Poached Eggs, Scrambled Eggs, or Omelets with Auto Shut Off Feature - Aqua, 5.5 Inch (DEC005AQ)",
        "price": "19.99",
        "priceValue": 19.99,
        "category": "appliances",
        "image": "https://m.media-amazon.com/images/I/617RjAx+UkL._AC_SL1500_.jpg",
        "rating": 4.6,
        "affiliateLink": "https://amzn.to/42uM2fA",
        "featured": false
    },
    {
        "id": 7032,
        "title": "KitchenAid Ribbed Soft Silicone Oven Mitt Set, 7\"x13\", Milkshake 2 Count",
        "price": "18.99",
        "priceValue": 18.99,
        "category": "appliances",
        "image": "https://m.media-amazon.com/images/I/617z6N3l59L._AC_SL1500_.jpg",
        "rating": 4.7,
        "affiliateLink": "https://amzn.to/46tsSbg",
        "featured": false
    },
    {
        "id": 7033,
        "title": "Electric Mason Jar Vacuum Sealer Kit for Wide Mouth and Regular Mouth Mason Jars",
        "price": "26.99",
        "priceValue": 26.99,
        "category": "appliances",
        "image": "https://m.media-amazon.com/images/I/71AdQPBUYGL._AC_SL1500_.jpg",
        "rating": 4.4,
        "affiliateLink": "https://amzn.to/3KaaOvh",
        "featured": false
    },
    {
        "id": 7034,
        "title": "Magic Bullet Blender, Small, Silver, 11 Piece Set",
        "price": "38.79",
        "priceValue": 38.79,
        "category": "appliances",
        "image": "https://m.media-amazon.com/images/I/61w2Tj7r0BL._AC_SL1500_.jpg",
        "rating": 4.4,
        "affiliateLink": "https://amzn.to/4nv5QaE",
        "featured": false
    },
    {
        "id": 7035,
        "title": "Mixing Bowls with Airtight Lids Set, 26PCS Stainless Steel Khaki Bowls with Grater Attachments, Non-Slip Bottoms & Kitchen Gadgets Set, Size 7, 4, 2.5, 2.0,1.5, 1QT, Great for Mixing & Serving",
        "price": "35.28",
        "priceValue": 35.28,
        "category": "appliances",
        "image": "https://m.media-amazon.com/images/I/71XR3lo00cL._AC_SL1500_.jpg",
        "rating": 4.7,
        "affiliateLink": "https://amzn.to/47PN7SS",
        "featured": false
    },
    {
        "id": 7036,
        "title": "Hamilton Beach Dual Breakfast Sandwich Maker with Timer, Ready in 5 Minutes, Removable Dishwasher Safe PFAS-Free Non-Stick Egg Cooker Ring, Silver (25490MNA)",
        "price": "49.99",
        "priceValue": 49.99,
        "category": "appliances",
        "image": "https://m.media-amazon.com/images/I/81ky0potEEL._AC_SL1500_.jpg",
        "rating": 4.6,
        "affiliateLink": "https://amzn.to/3VTtuBZ",
        "featured": false
    },
    {
        "id": 7037,
        "title": "Kitchen Mama Auto Electric Can Opener: Open Your Cans with A Simple Press of Button - Automatic, Hands Free, Smooth Edge, Food-Safe, Battery Operated, YES YOU CAN (White)",
        "price": "29.99",
        "priceValue": 29.99,
        "category": "appliances",
        "image": "https://m.media-amazon.com/images/I/71QUaFo11pL._AC_SL1500_.jpg",
        "rating": 4.2,
        "affiliateLink": "https://amzn.to/3IfOujl",
        "featured": false
    },
    {
        "id": 7038,
        "title": "Hamilton Beach Power Elite Wave Action Blender For Smoothies, 40 Oz Glass Jar, 12 Functions Including Puree, Crush Ice, 700 Watts - Black (58148A)",
        "price": "39.95",
        "priceValue": 39.95,
        "category": "appliances",
        "image": "https://m.media-amazon.com/images/I/71k1RTjfAhL._AC_SL1500_.jpg",
        "rating": 4.2,
        "affiliateLink": "https://amzn.to/4gtufex",
        "featured": false
    },
    {
        "id": 7039,
        "title": "BISSELL® Steam Shot™ OmniReach handheld portable steam cleaner for tile, grout, windows, bathrooms, kitchens, fabric steaming tool, includes 10 tools",
        "price": "33.87",
        "priceValue": 33.87,
        "category": "appliances",
        "image": "https://m.media-amazon.com/images/I/71SObM77ztL._AC_SL1500_.jpg",
        "rating": 4,
        "affiliateLink": "https://amzn.to/47PNtZI",
        "featured": false
    },
    {
        "id": 7040,
        "title": "AquaCare High Pressure 8-mode Handheld Shower Head - Anti-clog Nozzles, Built-in Power Wash to Clean Tub, Tile & Pets, Extra Long 6 ft. Stainless Steel Hose, Wall & Overhead Brackets",
        "price": "26.94",
        "priceValue": 26.94,
        "category": "appliances",
        "image": "https://m.media-amazon.com/images/I/81deB0wkLWL._AC_SL1500_.jpg",
        "rating": 4.6,
        "affiliateLink": "https://amzn.to/46rtQou",
        "featured": false
    },
    {
        "id": 7041,
        "title": "Wheat Straw Cups 6 PCS Good Alternative to Plastic Reusable Cups 12 oz Unbreakable Drinking Cup Reusable Dishwasher Safe Water Plastic Glasses with 6 Colors",
        "price": "12.97",
        "priceValue": 12.97,
        "category": "appliances",
        "image": "https://m.media-amazon.com/images/I/71gO9ZDqaZL._SL1500_.jpg",
        "rating": 4.6,
        "affiliateLink": "https://amzn.to/4gsryKa",
        "featured": false
    },
    {
        "id": 7042,
        "title": "Fullstar The Original Pro Chopper - Vegetable Chopper and Spiralizer, Food Chopper with Container, Fruit Slicer, Kitchen Gadgets & Accessories, Home Essentials (4 in 1, White)",
        "price": "26.99",
        "priceValue": 26.99,
        "category": "appliances",
        "image": "https://m.media-amazon.com/images/I/81lnspra9XL._AC_SL1500_.jpg",
        "rating": 4.5,
        "affiliateLink": "https://amzn.to/3VTZuWy",
        "featured": false
    },
    {
        "id": 7043,
        "title": "Hamilton Beach 6-Speed Electric Hand Mixer with Whisk, Traditional Beaters, Snap-On Storage Case, 250 Watts, White",
        "price": "27.95",
        "priceValue": 27.95,
        "category": "appliances",
        "image": "https://m.media-amazon.com/images/I/71VaQ-OzOJL._AC_SL1500_.jpg",
        "rating": 4.5,
        "affiliateLink": "https://amzn.to/41Z5D7y",
        "featured": false
    },
    {
        "id": 7044,
        "title": "kelamayi Upgrade Broom and Dustpan Set, Self-Cleaning with Dustpan Teeth, Indoor&Outdoor Sweeping, Ideal for Dog Cat Pets Home Use, Stand Up Broom and Dustpan (Gray&Orange)",
        "price": "26.99",
        "priceValue": 26.99,
        "category": "appliances",
        "image": "https://m.media-amazon.com/images/I/61zELlfqTPL._AC_SL1500_.jpg",
        "rating": 4.4,
        "affiliateLink": "https://amzn.to/4pt3VVZ",
        "featured": false
    },
    {
        "id": 7045,
        "title": "Crock-Pot 7 Quart Oval Manual Slow Cooker, Stainless Steel (SCV700-S-BR), Versatile Cookware for Large Families or Entertaining",
        "price": "41.11",
        "priceValue": 41.11,
        "category": "appliances",
        "image": "https://m.media-amazon.com/images/I/81s15a8-lGL._AC_SL1500_.jpg",
        "rating": 4.6,
        "affiliateLink": "https://amzn.to/3VoBz1l",
        "featured": false
    },
    {
        "id": 7046,
        "title": "Chefman XL Electric Griddle with Removable Temperature Control, Immersible Flat Top Grill, Burger, Eggs, Pancake Griddle, Nonstick Extra Large Cooking Surface, Slide Out Drip Tray, 10 x 20 Inch",
        "price": "36.03",
        "priceValue": 36.03,
        "category": "appliances",
        "image": "https://m.media-amazon.com/images/I/71t70sZjHpL._AC_SL1500_.jpg",
        "rating": 4.6,
        "affiliateLink": "https://amzn.to/3ItK9ZO",
        "featured": false
    },
    {
        "id": 7047,
        "title": "SENSARTE Nonstick Ceramic Frying Pan with Lid 8/9.5/10/11/12.5 Inch Omelet Pan Skillet, Free of Intentionally Added PFAS/PTFE Non-toxic Chef's Pan Induction Compatible Pan, Heat Resistant Handle",
        "price": "31.99",
        "priceValue": 31.99,
        "category": "appliances",
        "image": "https://m.media-amazon.com/images/I/71ckUw5PPoL._AC_SL1500_.jpg",
        "rating": 4.5,
        "affiliateLink": "https://amzn.to/4moLLSu",
        "featured": false
    },
    {
        "id": 7048,
        "title": "QCen Juicer Machine, 500W Centrifugal Juicer Extractor with Wide Mouth 3” Feed Chute for Fruit Vegetable, Easy to Clean, Stainless Steel, BPA-free (Black)",
        "price": "45.99",
        "priceValue": 45.99,
        "category": "appliances",
        "image": "https://m.media-amazon.com/images/I/71nonehjNMS._AC_SL1500_.jpg",
        "rating": 4.2,
        "affiliateLink": "https://amzn.to/4mqSxHs",
        "featured": false
    },
    {
        "id": 7049,
        "title": "Lodge Reversible Cast Iron Grill/Griddle – 9.5 x 16.75 Inch Pre-Seasoned Cooking Surface – Flat & Ribbed Sides – Use on Stove, Grill, or Campfire – Made in the USA – Heavy-Duty, Black",
        "price": "39.90",
        "priceValue": 39.9,
        "category": "appliances",
        "image": "https://m.media-amazon.com/images/I/71B0CYDQJhL._AC_SL1250_.jpg",
        "rating": 4.5,
        "affiliateLink": "https://amzn.to/46EKBO9",
        "featured": false
    },
    {
        "id": 7050,
        "title": "OVENTE Electric Deep Fryer 2 Liter Capacity, 1500 Watt Lid with Viewing Window and Odor Filter, Adjustable Temperature, Removable Frying Basket and Easy to Clean Stainless Steel Body, Silver FDM2201BR",
        "price": "25.19",
        "priceValue": 25.19,
        "category": "appliances",
        "image": "https://m.media-amazon.com/images/I/71Nhb9wugDL._AC_SL1500_.jpg",
        "rating": 4.1,
        "affiliateLink": "https://amzn.to/4gvhOyZ",
        "featured": false
    },
    {
        "id": 7051,
        "title": "Nostalgia Vintage Hard and Sugar Free Candy Countertop Cotton Candy Maker, Includes 2 Reusable Cones And Sugar Scoop – Pink",
        "price": "45.99",
        "priceValue": 45.99,
        "category": "appliances",
        "image": "https://m.media-amazon.com/images/I/71gvwKoU+QL._AC_SL1500_.jpg",
        "rating": 4.3,
        "affiliateLink": "https://amzn.to/48pxSQH",
        "featured": false
    },
    {
        "id": 7052,
        "title": "ROYAL CRAFT WOOD Wooden Cutting Boards for Kitchen Meal Prep & Serving - Bamboo Wood Serving Board Set with Deep Juice Groove Side Handles - Charcuterie & Chopping Butcher Block for Meat (3 Pcs)",
        "price": "34.52",
        "priceValue": 34.52,
        "category": "appliances",
        "image": "https://m.media-amazon.com/images/I/71TVPOOSysL._AC_SL1500_.jpg",
        "rating": 4.4,
        "affiliateLink": "https://amzn.to/4mHbsy5",
        "featured": false
    },
    {
        "id": 7053,
        "title": "Veken Coffee Canister with Window,Airtight Stainless Steel Container,Home Kitchen Food Storage Organizers for Grounds,Beans,Espresso,Rice,Tea,Sugar,Cereal, Flour,Scoop,Bar Accessories,Gifts,22OZ,Black",
        "price": "31.38",
        "priceValue": 31.38,
        "category": "appliances",
        "image": "https://m.media-amazon.com/images/I/715AW1fC7zL._AC_SL1500_.jpg",
        "rating": 4.8,
        "affiliateLink": "https://amzn.to/3K9RdeQ",
        "featured": false
    },
    {
        "id": 7054,
        "title": "BLACK+DECKER Coffee Maker with Vortex Technology, Non-Drip Carafe, Easy Pour, Removable Filter Basket, Easy On/Off Switch",
        "price": "29.44",
        "priceValue": 29.44,
        "category": "appliances",
        "image": "https://m.media-amazon.com/images/I/51r-kXmr2jL._AC_SL1291_.jpg",
        "rating": 4.4,
        "affiliateLink": "https://amzn.to/4gr1P4K",
        "featured": false
    },
    {
        "id": 7055,
        "title": "Egg Poacher - Eggssentials Poached Egg Maker, Stainless Steel Egg Poaching Pan, Poached Eggs Cooker Food Grade Safe PFOA Free with Spatula.",
        "price": "39.97",
        "priceValue": 39.97,
        "category": "appliances",
        "image": "https://m.media-amazon.com/images/I/716CeABPpyL._AC_SL1500_.jpg",
        "rating": 4.7,
        "affiliateLink": "https://amzn.to/4gF2S1d",
        "featured": false
    },
    {
        "id": 7056,
        "title": "Dash Deluxe No-Drip Waffle Iron Maker Machine 1200W + Hash Browns, or Any Breakfast, Lunch, & Snacks with Easy Clean, Non-Stick + Mess Free Sides, Aqua",
        "price": "47.72",
        "priceValue": 47.72,
        "category": "appliances",
        "image": "https://m.media-amazon.com/images/I/81gqG6iVMYL._AC_SL1500_.jpg",
        "rating": 4.6,
        "affiliateLink": "https://amzn.to/4nbSwsc",
        "featured": false
    },
    {
        "id": 7057,
        "title": "FENCHILIN Lighted Makeup Mirror Hollywood Mirror Vanity Makeup Mirror with Light Smart Touch Control 3Colors Dimmable Light Detachable 10X Magnification 360°Rotation(White)",
        "price": "49.49",
        "priceValue": 49.49,
        "category": "appliances",
        "image": "https://m.media-amazon.com/images/I/61JIHImDNXL._AC_SL1500_.jpg",
        "rating": 4.7,
        "affiliateLink": "https://amzn.to/47QOhxu",
        "featured": false
    }
];

// Export for use in main script
if (typeof module !== 'undefined' && module.exports) {
    module.exports = allProductsData;
}