# GitHub Pages configuration
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Site settings
title: "Amazon Gift Guide - Find Perfect Gifts by Budget"
description: "Discover amazing gift ideas organized by budget - under $10, $50, $100 and more. Curated Amazon products for every occasion."
url: "https://yourusername.github.io"
baseurl: "/repository-name"

# SEO settings
lang: en_US
author: "Your Name"

# Social media (optional)
twitter:
  username: yourusername
facebook:
  app_id: your_app_id
  username: yourusername

# Google Analytics (optional)
google_analytics: YOUR_TRACKING_ID

# Exclude files from processing
exclude:
  - README.md
  - .gitignore
  - .git/